# Generated by Django 5.1.1 on 2024-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
