# Generated by Django 5.1.1 on 2024-10-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_alter_product_category_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Listing Report', 'verbose_name_plural': 'Listing Reports'},
        ),
    ]
